spring:
  datasource:
    username: "root"
    password: "root"
    url: "jdbc:mysql://localhost:3306/zuccbiosphere?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
    driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 5
        max-idle: 1
        min-idle: 1
        max-wait: 5000
    timeout: 5000